require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.dap")
require("plugins.telescope")
require("plugins.dashboard")
require("plugins.hlchunk")
require("plugins.runcode")
require("plugins.cursorline")
require("plugins.themery")
require("plugins.smoothcursor")
require("plugins.im-switch")
require("plugins.lastplace")
require("plugins.foldbracket")
require("plugins.accelerated-jk")
require("plugins.lsp-signature")

-- require("plugins.shade") -- 变暗焦点窗口之外的窗口
